/**
 * JSON Schema → C# 클래스 생성기.
 *
 * ARCH-02: "스키마는 단일 정의에서 TS 타입과 C# 클래스를 양쪽으로 코드 생성한다 —
 * 손으로 맞추면 반드시 어긋난다."
 *
 * 생성 대상은 **데이터 전송 객체뿐이다.** 규칙은 절대 넘어가지 않는다 — sim은 TS에만
 * 있고 Unity에는 규칙이 존재하지 않아야 한다. 그래서 이 생성기는 스키마의 모양만 읽고
 * 기본값·검증·판정은 아무것도 만들지 않는다.
 *
 * 생성물은 `[Serializable]` POCO다. Unity의 JsonUtility가 읽을 수 있고,
 * discriminated union은 C#에 대응물이 없으므로 **필드 합집합 + type 판별자**로 편다.
 */

export interface JsonSchema {
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  enum?: unknown[];
  const?: unknown;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  $ref?: string;
  $defs?: Record<string, JsonSchema>;
  additionalProperties?: boolean | JsonSchema;
  nullable?: boolean;
}

export interface EmitOptions {
  readonly namespace: string;
  /** 생성된 파일 머리말에 넣을 경고문 */
  readonly banner?: string;
}

interface EmitState {
  readonly classes: Map<string, string>;
  readonly enums: Map<string, string[]>;
  readonly options: EmitOptions;
}

export function emitCSharp(
  schemas: Record<string, JsonSchema>,
  options: EmitOptions,
): string {
  const state: EmitState = { classes: new Map(), enums: new Map(), options };

  for (const [name, schema] of Object.entries(schemas)) {
    buildType(name, schema, state);
  }

  const banner =
    options.banner ??
    [
      "// <auto-generated>",
      "//   packages/protocol 의 zod 정의에서 생성됨. 직접 고치지 마라.",
      "//   다시 만들려면: npm run codegen:csharp",
      "//",
      "//   여기에는 데이터 모양만 있다. 규칙은 서버(packages/sim)에만 존재한다 — ARCH-02",
      "// </auto-generated>",
    ].join("\n");

  const body = [
    ...[...state.enums].map(([name, values]) => emitEnum(name, values)),
    ...state.classes.values(),
  ].join("\n\n");

  return `${banner}

using System;
using System.Collections.Generic;

namespace ${options.namespace}
{
${indent(body, 1)}
}
`;
}

/* ------------------------------------------------------------------ 내부 */

function buildType(name: string, schema: JsonSchema, state: EmitState): string {
  // union — C#에 대응물이 없으므로 필드 합집합으로 편다.
  // 판별자(type)로 갈라 읽는 것은 소비하는 쪽의 몫이다.
  const variants = schema.anyOf ?? schema.oneOf;
  if (variants && variants.length > 0) {
    return buildUnion(name, variants, state);
  }

  if (schema.enum && schema.enum.length > 0) {
    // 문자열 열거는 C# enum이 아니라 const 모음으로 낸다.
    // enum으로 만들면 서버가 값을 하나 추가했을 때 파싱이 실패하는데,
    // 프로토콜은 서버가 앞서 나가는 쪽이 정상이라 깨지면 안 된다.
    state.enums.set(name, schema.enum.map(String));
    return "string";
  }

  if (schema.type === "object" || schema.properties) {
    buildClass(name, schema, state);
    return name;
  }

  return primitive(schema);
}

function buildUnion(name: string, variants: JsonSchema[], state: EmitState): string {
  const merged: Record<string, JsonSchema> = {};
  const discriminators: string[] = [];

  for (const variant of variants) {
    for (const [key, prop] of Object.entries(variant.properties ?? {})) {
      // 판별자는 리터럴이라 variant마다 다르다 — 필드는 문자열로 뭉개되
      // 값 자체는 따로 모아 상수로 낸다. Unity가 의도를 보내려면 이 문자열이 필요하다.
      if (key === "type" && typeof prop.const === "string") {
        merged[key] = { type: "string" };
        if (!discriminators.includes(prop.const)) discriminators.push(prop.const);
        continue;
      }
      merged[key] ??= prop;
    }
  }

  if (discriminators.length > 0) {
    state.enums.set(`${name}Type`, discriminators);
  }

  // union의 필드는 전부 선택적이다 — 어느 variant냐에 따라 없을 수 있다
  buildClass(name, { type: "object", properties: merged, required: [] }, state);
  return name;
}

function buildClass(name: string, schema: JsonSchema, state: EmitState): void {
  if (state.classes.has(name)) return;
  state.classes.set(name, ""); // 재귀 방지용 자리 선점

  const required = new Set(schema.required ?? []);
  const fields: string[] = [];

  for (const [key, prop] of Object.entries(schema.properties ?? {})) {
    const nested = `${name}${pascal(key)}`;
    const type = resolve(prop, nested, state);
    const optional = !required.has(key);
    fields.push(
      `${optional ? "// 선택적 — variant에 따라 없을 수 있다\n" : ""}public ${type} ${key};`,
    );
  }

  state.classes.set(
    name,
    `[Serializable]\npublic class ${name}\n{\n${indent(fields.join("\n"), 1)}\n}`,
  );
}

function resolve(schema: JsonSchema, fallbackName: string, state: EmitState): string {
  const variants = schema.anyOf ?? schema.oneOf;

  // nullable은 [T, null] 형태로 온다 — C#에서는 참조형이면 그대로 null이 된다
  if (variants && variants.length === 2) {
    const nonNull = variants.find((v) => v.type !== "null");
    if (nonNull && variants.some((v) => v.type === "null")) {
      return nullable(resolve(nonNull, fallbackName, state));
    }
  }

  if (variants && variants.length > 0) {
    return buildUnion(fallbackName, variants, state);
  }

  if (schema.enum && schema.enum.length > 0) {
    state.enums.set(fallbackName, schema.enum.map(String));
    return "string";
  }

  if (schema.type === "array") {
    const item = schema.items ? resolve(schema.items, `${fallbackName}Item`, state) : "string";
    // Unity JsonUtility는 List<T>보다 배열이 안전하다
    return `${item}[]`;
  }

  if (schema.type === "object" || schema.properties) {
    buildClass(fallbackName, schema, state);
    return fallbackName;
  }

  return primitive(schema);
}

function primitive(schema: JsonSchema): string {
  const type = Array.isArray(schema.type) ? schema.type[0] : schema.type;
  switch (type) {
    case "integer":
      return "int";
    case "number":
      // 스냅샷의 수치는 ms·비율이 섞여 있다. float로 받으면 큰 ms에서 정밀도를 잃는다.
      return "double";
    case "boolean":
      return "bool";
    case "null":
      return "string";
    default:
      return "string";
  }
}

/** 값형만 ? 를 붙인다. 문자열·배열·클래스는 이미 null을 담을 수 있다. */
function nullable(type: string): string {
  return ["int", "double", "bool"].includes(type) ? `${type}?` : type;
}

function emitEnum(name: string, values: string[]): string {
  const consts = values
    .map((value) => `public const string ${pascal(value)} = "${value}";`)
    .join("\n");
  return `/// <summary>${name} 이 가질 수 있는 값. 서버가 값을 추가해도 깨지지 않도록 enum이 아니라 상수로 둔다.</summary>\npublic static class ${name}Values\n{\n${indent(consts, 1)}\n}`;
}

function pascal(value: string): string {
  return value
    .replace(/[^a-zA-Z0-9]+(.)?/g, (_, chr: string | undefined) =>
      chr ? chr.toUpperCase() : "",
    )
    .replace(/^./, (chr) => chr.toUpperCase());
}

function indent(text: string, level: number): string {
  const pad = "    ".repeat(level);
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? pad + line : line))
    .join("\n");
}
