import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { allJsonSchemas } from "@sad/protocol/schemas";
import { allItemLabels, ZONES, zoneInfo } from "@sad/sim";
import { emitCSharp, type JsonSchema } from "./emit.js";

/**
 * 프로토콜 C# 생성기.
 *
 * 출력물은 Unity 프로젝트가 그대로 가져다 쓴다. 손으로 고치면 다음 실행에서 덮어써지고,
 * 그게 의도다 — 스키마와 어긋난 C#이 살아남으면 안 된다.
 */
const OUT = resolve(process.argv[2] ?? "unity/Assets/Scripts/Generated/Protocol.cs");

const schemas = allJsonSchemas() as Record<string, JsonSchema>;
const source = emitCSharp(schemas, { namespace: "SoldierADay.Protocol" });

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, source, "utf8");

console.log(`[csharpgen] ${Object.keys(schemas).length}개 타입 → ${OUT}`);

/**
 * 구역 이름표.
 *
 * 스냅샷은 `zone`을 `"Z03"` 같은 id로만 보낸다 — 이름은 판정이 아니므로 매 틱
 * 실어 보낼 이유가 없다. 그렇다고 Unity가 손으로 표를 들고 있으면 구역이 늘 때마다
 * 어긋나므로(예전 8구역 표가 딱 그랬다), sim의 `zones.json`에서 같이 생성한다.
 *
 * 여기 담기는 것은 **표시용 이름뿐이다.** 인접·열원·실내 같은 판정값은 넘기지
 * 않는다 — 그걸 클라가 알면 곧 클라가 판정하게 된다(ARCH-02).
 */
const ZONES_OUT = join(dirname(OUT), "Zones.cs");
const rows = ZONES.map((id) => {
  const info = zoneInfo(id);
  const building = info.buildingName ? `"${info.buildingName}"` : "null";
  return `            Add("${id}", "${info.name}", "${info.short}", ${building});`;
}).join("\n");

const itemRows = Object.entries(allItemLabels())
  .map(([id, label]) => `            ["${id}"] = "${label}",`)
  .join("\n");

writeFileSync(
  ZONES_OUT,
  `// <auto-generated>
//   packages/sim/data/zones.json 에서 생성됨. 직접 고치지 마라.
//   다시 만들려면: npm run codegen:csharp
// </auto-generated>
using System.Collections.Generic;

namespace SoldierADay.Net
{
    /// <summary>구역 표시 이름. 규칙과 무관하다 — 판정은 전부 서버에 있다(ARCH-02)</summary>
    public static class ZoneNames
    {
        private static readonly Dictionary<string, string> Names = new Dictionary<string, string>();
        private static readonly Dictionary<string, string> Shorts = new Dictionary<string, string>();
        private static readonly Dictionary<string, string> Buildings = new Dictionary<string, string>();
        private static readonly List<string> Order = new List<string>();

        static ZoneNames()
        {
${rows}
        }

        private static void Add(string id, string name, string small, string building)
        {
            Names[id] = name;
            Shorts[id] = small;
            if (building != null) Buildings[id] = building;
            Order.Add(id);
        }

        /// <summary>이름. 모르는 id는 그대로 돌려준다 — 빈칸보다 낫다</summary>
        public static string Of(string zone) =>
            zone != null && Names.TryGetValue(zone, out var name) ? name : zone;

        /// <summary>
        /// 지도용 짧은 이름.
        ///
        /// 좁은 방에 긴 이름을 넣으면 잘리고, **잘린 이름은 없는 이름과 같다.**
        /// </summary>
        public static string ShortOf(string zone) =>
            zone != null && Shorts.TryGetValue(zone, out var s) ? s : Of(zone);

        /// <summary>속한 동. 야외면 null</summary>
        public static string BuildingOf(string zone) =>
            zone != null && Buildings.TryGetValue(zone, out var b) ? b : null;

        /// <summary>"생활관동 · 세탁 · 건조실" — 어느 건물 안인지까지 붙인다</summary>
        public static string FullOf(string zone)
        {
            var building = BuildingOf(zone);
            return building == null ? Of(zone) : $"{building} · {Of(zone)}";
        }

        public static IReadOnlyList<string> All => Order;
    }

    /// <summary>보급 품목 표시 이름. packages/sim/data/supply.json 에서 생성됨</summary>
    public static class ItemNames
    {
        private static readonly Dictionary<string, string> Labels = new Dictionary<string, string>
        {
${itemRows}
        };

        /// <summary>모르는 id는 그대로 — 빈칸보다 낫다</summary>
        public static string Of(string id) =>
            id != null && Labels.TryGetValue(id, out var label) ? label : id;
    }
}
`,
  "utf8",
);

console.log(`[csharpgen] 구역 ${ZONES.length}개 → ${ZONES_OUT}`);
