import { describe, expect, it } from "vitest";
import { allJsonSchemas } from "@sad/protocol/schemas";
import { emitCSharp, type JsonSchema } from "../src/emit.js";

const schemas = allJsonSchemas() as Record<string, JsonSchema>;
const source = emitCSharp(schemas, { namespace: "SoldierADay.Protocol" });

describe("ARCH-02 — 단일 정의에서 C#을 생성한다", () => {
  it("스냅샷의 모든 최상위 필드가 C#에 나타난다", () => {
    // 손으로 맞추면 반드시 어긋난다 — 그래서 스키마와 생성물을 직접 비교한다
    const snapshot = schemas.Snapshot;
    const fields = Object.keys(snapshot?.properties ?? {});

    expect(fields.length).toBeGreaterThan(10);
    for (const field of fields) {
      expect(source, `Snapshot.${field}`).toContain(` ${field};`);
    }
  });

  it("의도 15종의 판별자가 전부 상수로 남는다", () => {
    // 하달 창 조기 종료 신고(delegationDone)가 15번째로 늘었다 — 시간이 멈추는
    // 버그 수정의 일부다 (packages/protocol/src/index.ts intentSchema)
    const intent = schemas.Intent;
    const variants = intent?.anyOf ?? intent?.oneOf ?? [];
    expect(variants.length).toBe(15);

    for (const variant of variants) {
      const literal = variant.properties?.type?.const;
      if (typeof literal !== "string") continue;
      expect(source, `Intent.${literal}`).toContain(`"${literal}"`);
    }
  });

  it("규칙은 넘어가지 않는다 — 데이터 모양만 있다", () => {
    // sim의 판정·밸런스가 C#에 새어나가면 ARCH-02가 무너진다
    for (const banned of ["judgeDay", "PARTIAL_SUCCESS", "DISCIPLINE_FLOOR", "reliefsUsed"]) {
      expect(source, banned).not.toContain(banned);
    }
    // 생성물에 로직이 없다는 것 — 메서드 본문이 없어야 한다
    expect(source).not.toMatch(/\breturn\b/);
    expect(source).not.toMatch(/\bif\s*\(/);
  });

  it("문자열 열거는 enum이 아니라 상수다", () => {
    // enum으로 만들면 서버가 값을 하나 추가했을 때 파싱이 실패한다.
    // 프로토콜은 서버가 앞서 나가는 쪽이 정상이라 그렇게 깨지면 안 된다.
    expect(source).toContain("public static class SnapshotPhaseIdValues");
    expect(source).not.toMatch(/^\s*public enum /m);
  });

  it("시드와 RNG 상태는 C#에도 존재하지 않는다", () => {
    expect(source).not.toContain("rngState");
    expect(source).not.toMatch(/\bseed\b/);
  });

  it("배열은 List가 아니라 배열로 낸다 — Unity JsonUtility 제약", () => {
    expect(source).toContain("[] members;");
    expect(source).toContain("[] quests;");
    expect(source).not.toContain("List<");
  });

  it("생성물은 결정론적이다 — 같은 스키마면 같은 파일", () => {
    const again = emitCSharp(schemas, { namespace: "SoldierADay.Protocol" });
    expect(again).toBe(source);
  });

  it("직접 고치지 말라는 경고가 머리에 붙는다", () => {
    expect(source.startsWith("// <auto-generated>")).toBe(true);
    expect(source).toContain("직접 고치지 마라");
  });
});

describe("C# 문법 형태", () => {
  it("중괄호가 짝이 맞는다", () => {
    const open = (source.match(/\{/g) ?? []).length;
    const close = (source.match(/\}/g) ?? []).length;
    expect(open).toBe(close);
  });

  it("모든 클래스에 [Serializable]이 붙는다 — JsonUtility 요구사항", () => {
    const classes = source.match(/^\s*public class (\w+)/gm) ?? [];
    const serializable = source.match(/\[Serializable\]/g) ?? [];
    expect(serializable.length).toBe(classes.length);
  });

  it("네임스페이스가 하나다", () => {
    expect((source.match(/^namespace /gm) ?? []).length).toBe(1);
  });
});
